version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    volumes:
      - mongo-db:/data/db
    networks:
      - testAppNetwork
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53000:3000"
    volumes:
      - .:/app/
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - testAppNetwork

volumes:
  mongo-db:

networks:
  testAppNetwork:
    name: test-app-network
